# Generated by Django 5.0.6 on 2025-04-13 13:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_band_min', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('price_band_max', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('open_date', models.DateField()),
                ('close_date', models.DateField()),
                ('issue_size', models.DecimalField(decimal_places=2, help_text='Issue size in rupees', max_digits=20)),
                ('issue_type', models.CharField(help_text='e.g., Fresh Issue, OFS, Combination', max_length=100)),
                ('listing_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('open', 'Open'), ('closed', 'Closed'), ('listed', 'Listed')], default='upcoming', max_length=20)),
                ('ipo_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('listing_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_market_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rhp_document', models.FileField(blank=True, help_text='Red Herring Prospectus', null=True, upload_to='ipo_documents/rhp/')),
                ('drhp_document', models.FileField(blank=True, help_text='Draft Red Herring Prospectus', null=True, upload_to='ipo_documents/drhp/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipos', to='ipo_api.company')),
            ],
            options={
                'verbose_name': 'IPO',
                'verbose_name_plural': 'IPOs',
                'ordering': ['-open_date'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('is_client', models.BooleanField(default=False)),
                ('api_key', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
